color_scheme:
  common:
    theme: '#F5C518'      
    link : '#F1B90B'
    button: '#00E5FF'
    hover: '#FF8A00'
    inner: '#FFFFFF'
    selection: 'alpha(#00B2FF, 0.2)'
  light:
    site_bg:   '#0D1117'
    site_inner: '#111827'
    site_footer: '#9CA3AF'
    card:      '#0F172A'
    text:      '#E5E7EB'
    block:     '#0B1220'
    codeblock: '#0B1220'
    inlinecode: '#F59E0B'
  dark:
    site_bg:   '#0B1020'
    site_inner: '#E5E7EB'
    site_footer: '#A3A3A3'
    card:      '#111827'
    text:      '#E6E9EF'
    block:     '#0F172A'
    codeblock: '#111827'
    inlinecode: '#F59E0B'